export const SAVE_POST_FULLFILLED = 'SAVE_POST_FULLFILLED';
export const SAVE_POST_PENDING = 'SAVE_POST_PENDING';
export const SAVE_POST_REJECTED = 'SAVE_POST_REJECTED';

export const GET_POSTS_FULLFILLED = 'GET_POSTS_FULLFILLED';
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';
export const GET_POSTS_REJECTED = 'GET_POSTS_REJECTED';

export const LOGOUT_FULLFILLED = 'LOGOUT_FULLFILLED';
