export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_REGISTER_USER = 'SET_REGISTER_USER';

export const LOGIN_FULLFILLED = 'LOGIN_FULLFILLED';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const LOGOUT_FULLFILLED = 'LOGOUT_FULLFILLED';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
