export const SEARCH_USERS_PENDING = 'SEARCH_USERS_PENDING';
export const SEARCH_USERS_FULLFILLED = 'SEARCH_USERS_FULLFILLED';
export const SEARCH_USERS_REJECTED = 'SEARCH_USERS_REJECTED';

export const FOLLOW_USERS_PENDING = 'FOLLOW_USERS_PENDING';
export const FOLLOW_USERS_FULLFILLED = 'FOLLOW_USERS_FULLFILLED';
export const FOLLOW_USERS_REJECTED = 'FOLLOW_USERS_REJECTED';

export const UNFOLLOW_USERS_PENDING = 'UNFOLLOW_USERS_PENDING';
export const UNFOLLOW_USERS_FULLFILLED = 'UNFOLLOW_USERS_FULLFILLED';
export const UNFOLLOW_USERS_REJECTED = 'UNFOLLOW_USERS_REJECTED';

export const GET_USER_FOLLOWINGS_PENDING = 'GET_USER_FOLLOWINGS_PENDING';
export const GET_USER_FOLLOWINGS_FULLFILLED = 'GET_USER_FOLLOWINGS_FULLFILLED';
export const GET_USER_FOLLOWINGS_REJECTED = 'GET_USER_FOLLOWINGS_REJECTED';

export const LOGOUT_FULLFILLED = 'LOGOUT_FULLFILLED';
