export const SEARCH_USERS_PENDING = 'SEARCH_USERS_PENDING';
export const SEARCH_USERS_FULLFILLED = 'SEARCH_USERS_FULLFILLED';
export const SEARCH_USERS_REJECTED = 'SEARCH_USERS_REJECTED';
export const FOLLOW_USERS_PENDING = 'FOLLOW_USERS_PENDING';
export const FOLLOW_USERS_FULLFILLED = 'FOLLOW_USERS_FULLFILLED';
export const FOLLOW_USERS_REJECTED = 'FOLLOW_USERS_REJECTED';
